--
-- PostgreSQL database dump
--

\restrict W0V3cCpOubRAAYsW0sIWSA4gFBgSbaFsW6Z2WigrJ7Kypd1fJClpYiIYWc3fsgY

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg13+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: client; Type: TABLE; Schema: public; Owner: shopwise_user
--

CREATE TABLE public.client (
    id bigint NOT NULL,
    email character varying(255),
    nom character varying(255),
    phone character varying(255),
    prenom character varying(255)
);


ALTER TABLE public.client OWNER TO shopwise_user;

--
-- Name: client_seq; Type: SEQUENCE; Schema: public; Owner: shopwise_user
--

CREATE SEQUENCE public.client_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.client_seq OWNER TO shopwise_user;

--
-- Name: clients; Type: TABLE; Schema: public; Owner: shopwise_user
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    nom character varying(255) NOT NULL,
    prenom character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    service_type character varying(255),
    fidelity_points integer,
    hash_password character varying(255)
);


ALTER TABLE public.clients OWNER TO shopwise_user;

--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: shopwise_user
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients_seq; Type: SEQUENCE; Schema: public; Owner: shopwise_user
--

CREATE SEQUENCE public.clients_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.clients_seq OWNER TO shopwise_user;

--
-- Name: commercant; Type: TABLE; Schema: public; Owner: shopwise_user
--

CREATE TABLE public.commercant (
    id bigint NOT NULL,
    nom character varying(255) NOT NULL
);


ALTER TABLE public.commercant OWNER TO shopwise_user;

--
-- Name: commercant_id_seq; Type: SEQUENCE; Schema: public; Owner: shopwise_user
--

ALTER TABLE public.commercant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commercant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commercants; Type: TABLE; Schema: public; Owner: shopwise_user
--

CREATE TABLE public.commercants (
    id bigint NOT NULL,
    nom character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.commercants OWNER TO shopwise_user;

--
-- Name: commercants_id_seq; Type: SEQUENCE; Schema: public; Owner: shopwise_user
--

ALTER TABLE public.commercants ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.commercants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rendezvous; Type: TABLE; Schema: public; Owner: shopwise_user
--

CREATE TABLE public.rendezvous (
    id bigint NOT NULL,
    appointment_date timestamp(6) without time zone NOT NULL,
    client_id bigint NOT NULL,
    commercant_id bigint NOT NULL,
    fidelity_points integer,
    service_type character varying(255),
    status character varying(255) NOT NULL
);


ALTER TABLE public.rendezvous OWNER TO shopwise_user;

--
-- Name: rendezvous_id_seq; Type: SEQUENCE; Schema: public; Owner: shopwise_user
--

ALTER TABLE public.rendezvous ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rendezvous_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: shopwise_user
--

COPY public.client (id, email, nom, phone, prenom) FROM stdin;
\.


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: shopwise_user
--

COPY public.clients (id, nom, prenom, email, phone, created_at, service_type, fidelity_points, hash_password) FROM stdin;
1	Dupont	Jean	jean.dupont@example.com	+33612345678	2026-08-15 22:07:18.826118	\N	\N	\N
2	Curie	Marie	marie.curie@example.com	\N	2026-08-16 15:34:50.186298	\N	\N	\N
4	Einstein	Albert	albert.einstein@gmail.com	0611223344	2026-08-20 13:47:53.809305	\N	\N	8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92
\.


--
-- Data for Name: commercant; Type: TABLE DATA; Schema: public; Owner: shopwise_user
--

COPY public.commercant (id, nom) FROM stdin;
\.


--
-- Data for Name: commercants; Type: TABLE DATA; Schema: public; Owner: shopwise_user
--

COPY public.commercants (id, nom, created_at) FROM stdin;
1	commercant 1	2026-08-20 12:24:39.483077
2	commercant 2	2026-08-20 12:24:43.365873
\.


--
-- Data for Name: rendezvous; Type: TABLE DATA; Schema: public; Owner: shopwise_user
--

COPY public.rendezvous (id, appointment_date, client_id, commercant_id, fidelity_points, service_type, status) FROM stdin;
1	2026-08-20 16:00:00	1	1	10	Consultation	completed
3	2026-08-22 14:21:00	4	1	10	Consultation	completed
2	2026-08-22 14:18:00	1	1	0	Consultation	scheduled
\.


--
-- Name: client_seq; Type: SEQUENCE SET; Schema: public; Owner: shopwise_user
--

SELECT pg_catalog.setval('public.client_seq', 1, false);


--
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: shopwise_user
--

SELECT pg_catalog.setval('public.clients_id_seq', 4, true);


--
-- Name: clients_seq; Type: SEQUENCE SET; Schema: public; Owner: shopwise_user
--

SELECT pg_catalog.setval('public.clients_seq', 1, false);


--
-- Name: commercant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: shopwise_user
--

SELECT pg_catalog.setval('public.commercant_id_seq', 1, false);


--
-- Name: commercants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: shopwise_user
--

SELECT pg_catalog.setval('public.commercants_id_seq', 2, true);


--
-- Name: rendezvous_id_seq; Type: SEQUENCE SET; Schema: public; Owner: shopwise_user
--

SELECT pg_catalog.setval('public.rendezvous_id_seq', 3, true);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: shopwise_user
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- Name: clients clients_email_key; Type: CONSTRAINT; Schema: public; Owner: shopwise_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_email_key UNIQUE (email);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: shopwise_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: commercant commercant_pkey; Type: CONSTRAINT; Schema: public; Owner: shopwise_user
--

ALTER TABLE ONLY public.commercant
    ADD CONSTRAINT commercant_pkey PRIMARY KEY (id);


--
-- Name: commercants commercants_pkey; Type: CONSTRAINT; Schema: public; Owner: shopwise_user
--

ALTER TABLE ONLY public.commercants
    ADD CONSTRAINT commercants_pkey PRIMARY KEY (id);


--
-- Name: rendezvous rendezvous_pkey; Type: CONSTRAINT; Schema: public; Owner: shopwise_user
--

ALTER TABLE ONLY public.rendezvous
    ADD CONSTRAINT rendezvous_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict W0V3cCpOubRAAYsW0sIWSA4gFBgSbaFsW6Z2WigrJ7Kypd1fJClpYiIYWc3fsgY

